name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run automated tests
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install --no-package-lock
    - run: npm test --workspaces --if-present
