name: Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run automated tests
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npx playwright install
      - run: npx playwright test
